### ISSUE TITLE
Create hex sticker

### ISSUE THREAD

**Issue by eddjberry** [r-leeds/logo#1]
As @gofraidh has suggested it'd be nice to make a hex sticker from the logo. @Robinlovelace recommended the package [hexSticker](https://github.com/GuangchuangYu/hexSticker) to do this.

If someone wants to do this then you could create a branch called hex-sticker and do the work on that branch then create a pull request linked to this issue (shout if you need any help from Robin or I with this)

**Comment by gofraidh** [comment]
![rleeds_hex_logo](https://user-images.githubusercontent.com/7356171/66788291-f873cd80-eede-11e9-9243-96d681891b5e.png)

The code should output this. Fonts were changed because url was printed weirdly with mono fonts and sadly the text arranging with the package allows only modification on x and y axis. Maybe there other way to arrange it.
